sudo: false
language: python

matrix:
    include:
      - python: 3.4
      - python: 3.5
      - python: 3.6
      - python: 3.7
        dist: xenial

env:
    - REPOSITORY_ORIGIN=smarthome

before_install:
    - sudo apt-get install libudev-dev
install:
    - pip install tox-travis virtualenv
    - pip install sphinx sphinx_rtd_theme recommonmark  
    - pip install "ruamel.yaml<=0.15.74"

script:
    - sh .travis.sh
